//@ui5-bundle uxbtpjoulewebclient/Component-preload.js
sap.ui.require.preload({
	"uxbtpjoulewebclient/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","uxbtpjoulewebclient/model/models"],function(e,t,n){"use strict";return e.extend("uxbtpjoulewebclient.Component",{metadata:{manifest:"json"},init:function(){var e=this._getRenderer();e.then(function(e){e.addHeaderEndItem({icon:"sap-icon://da",tooltip:"Joule",press:this._opneJoule.bind(this)},true,false)}.bind(this))},_opneJoule:function(e){window.open("https://cnjbs7.axshare.com/?id=yylh9o&p=joule&sc=2&dp=0&fn=0&c=1","popup","width=400,height=600,toolbar=0,location=0,top=600,left=1000")},_getRenderer:function(){var e=this,t=new jQuery.Deferred,n;e._oShellContainer=jQuery.sap.getObject("sap.ushell.Container");if(!e._oShellContainer){t.reject("Illegal state: shell container not available; this component must be executed in a unified shell runtime context.")}else{n=e._oShellContainer.getRenderer();if(n){t.resolve(n)}else{e._onRendererCreated=function(e){n=e.getParameter("renderer");if(n){t.resolve(n)}else{t.reject("Illegal state: shell renderer not available after recieving 'rendererLoaded' event.")}};e._oShellContainer.attachRendererCreatedEvent(e._onRendererCreated)}}return t.promise()}})});
},
	"uxbtpjoulewebclient/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("uxbtpjoulewebclient.controller.App",{onInit:function(){}})});
},
	"uxbtpjoulewebclient/i18n/i18n.properties":'# This is the resource bundle for uxbtpjoulewebclient\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Joule Plugin\n\n#YDES: Application description\nappDescription=An SAP Fiori Plugin.\n#XTIT: Main view title\ntitle=Joule Plugin\n\nflpTitle=Joule Plugin\n',
	"uxbtpjoulewebclient/manifest.json":'{"_version":"1.59.0","sap.app":{"id":"uxbtpjoulewebclient","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.12.5","toolsId":"90da66f6-2acd-42e9-b0df-6d179bcaa68f"},"crossNavigation":{"inbounds":{"jouleWebclient-Plugin":{"semanticObject":"jouleWebclient","action":"Plugin","title":"{{flpTitle}}","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.120.9","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"uxbtpjoulewebclient.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"uxbtpjoulewebclient.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":":?query:","target":["TargetApp"]}],"targets":{"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"}}},"rootView":{"viewName":"uxbtpjoulewebclient.view.App","type":"XML","async":true,"id":"App"}},"sap.cloud":{"public":true,"service":"uxbtpjoulewebclient"},"sap.flp":{"type":"plugin"}}',
	"uxbtpjoulewebclient/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"uxbtpjoulewebclient/view/App.view.xml":'<mvc:View controllerName="uxbtpjoulewebclient.controller.App"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"><content /></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
